---
title: "LAB2 - PARTE2 : Anne Gabriele - David Eduardo"
output: html_notebook
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(dplyr)
library(ggplot2)
library(plotly)
theme_set(theme_bw())
```

```{r}
enade_ccc = read_csv(here("/data/enade-ccc-2017.csv"), col_types = "cccdccdddc")
```
#1. Visualização interativa da Média Geral das Categorias por Estado

## Vetores com os estados brasileiros por região
```{r}
regiao_norte = c("AC", "RO", "AM", "RR", "PA", "AP", "TO") 
regiao_nordeste = c("MA", "CE", "PI", "BA", "SE", "AL", "PE", "PB", "RN")
regiao_centroeste = c("MT", "DF", "MS", "GO")
regiao_sudeste = c("MG", "ES", "RJ", "SP")
regiao_sul = c("PR", "SC", "RS")
```

## Calcula a media das medias de uma categoria por estado
```{r}
categoria_por_uf_ALDT = enade_ccc %>%
    filter(categoria == "Aprendizagem além do técnico") %>%
    group_by(UF) %>% summarise(media_aprendizagem=mean(media)) 

categoria_por_uf_CEG = enade_ccc %>%
    filter(categoria == "Curso em geral") %>%
    group_by(UF) %>% summarise(media_curso=mean(media)) 

categoria_por_uf_EAA = enade_ccc %>%
    filter(categoria == "Ensino, apoio e avaliacão") %>%
    group_by(UF) %>% summarise(media_eaa=mean(media)) 

categoria_por_uf_INFRA = enade_ccc %>%
    filter(categoria == "Infraestrutura") %>%
    group_by(UF) %>% summarise(media_infraestrutura=mean(media)) 

categoria_por_uf_OUTROS = enade_ccc %>%
    filter(categoria == "Outros") %>%
    group_by(UF) %>% summarise(media_outros=mean(media)) 
```

## Dataframe adaptado para a visualização
```{r}
media_geral_uf = enade_ccc %>%
    group_by(UF) %>% summarise(media_geral=mean(media))

regioes <- c("Norte", "Nordeste", "Nordeste", "Centro-oeste", "Centro-oeste", "Nordeste", "Centro-oeste","Nordeste", "Nordeste", "Nordeste", "Sul", "Sudeste", "Sul","Sul","Sudeste")

media_geral_uf$regiao = regioes
media_geral_uf$media_ALDT = categoria_por_uf_ALDT$media_aprendizagem
media_geral_uf$media_CEG = categoria_por_uf_CEG$media_curso
media_geral_uf$media_EAA = categoria_por_uf_EAA$media_eaa
media_geral_uf$media_INFRA = categoria_por_uf_INFRA$media_infraestrutura

media_geral_uf <- media_geral_uf[order(media_geral_uf$media_geral),]

```

```{r}

p <- plot_ly(media_geral_uf, x = ~UF, y = ~media_geral, color=~UF,  type = 'bar', name = ~UF,
            text = ~paste('Media Geral', media_geral,'\nAprendizagem além do técnico:', media_ALDT, '\nCurso em geral:', media_CEG, '\nEnsino, apoio e avaliação:', media_EAA, '\nInfraestrutura:', media_INFRA)) %>%
  layout(title = "Média Geral das Categorias por Estado",
         xaxis = list(title = "UF", tickangle = -45),
         yaxis = list(title = "Média Geral das Categorias"),
         margin = list(b = 100),
         barmode = 'group')

Sys.setenv("plotly_username"="anne.silva")
Sys.setenv("plotly_api_key"="U2NoMFKnaJJgAy4wdHYZ")
api_create(p, filename="media-geral-estado")
```
```{r}

aval_regiao = media_geral_uf %>%
    group_by(regiao) %>% summarise(media_ALDT=mean(media_ALDT), media_CEG=mean(media_CEG), media_EAA=mean(media_EAA), media_INFRA=mean(media_INFRA))

```
# 2.Visualização de cada Categoria por Região 
```{r}

```

```{r}

p <- plot_ly(aval_regiao, x = ~regiao, y = ~media_ALDT, type = 'bar', name = 'Aprendizagem além do técnico',
        marker = list(color = 'rgb(153, 153, 130)')) %>%
  add_trace(y = ~media_CEG, name = 'Curso em geral', marker = list(color = 'rgb(255, 153, 102)')) %>%
  add_trace(y = ~media_EAA, name = 'Ensino, apoio e avaliação', marker = list(color = 'rgb(255, 153, 153)')) %>%
  add_trace(y = ~media_INFRA, name = 'Infraestrutura', marker = list(color = 'rgb(204, 204, 255)')) %>%
  layout(title = 'Média das Categorias por Região',
         xaxis = list(
           title = "Região do Brasil",
           tickfont = list(
             size = 14,
             color = 'rgb(1, 1, 1)')),
         yaxis = list(
           title = 'Média da Categoria',
           titlefont = list(
             size = 16,
             color = 'rgb(1, 1, 1)'),
           tickfont = list(
             size = 14,
             color = 'rgb(1, 1, 1)')),
         legend = list(x = 0, y = 1, bgcolor = 'rgba(255, 255, 255, 0)', bordercolor = 'rgba(255, 255, 255, 0)'),
         barmode = 'group', bargap = 0.25, bargroupgap = 0.2)

Sys.setenv("plotly_username"="anne.silva")
Sys.setenv("plotly_api_key"="U2NoMFKnaJJgAy4wdHYZ")
api_create(p, filename="media-categoria-regiao")
```



