---
title: "Uma história em slides"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
#library(hrbrthemes)
#theme_set(theme_ipsum())

respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

cursos = respostas %>% 
    group_by(UF) %>% 
    summarise(n = n(), 
              media = mean(media))

criterios = respostas %>% 
    group_by(UF, categoria) %>% 
    summarise(media = mean(media))


```

estatico:

Como a UFCG esta em relação ao nordeste ??

````{r fig.height=16, fig.width=6}
NE <- c("PB", "PI", "MA", "PE", "CE", "AL", "SE", "RN", "BA")

respostas %>%
    group_by(UF) %>% 
    filter( UF %in% NE) %>% 
    ggplot(aes(x = UF, y  = media), color = UF ) +
    geom_point()    
        
respostas %>%
    filter(categoria != "Outros") %>%
    filter( UF %in% NE) %>% 
    ggplot(aes(x = reorder(tema, media), y = media, color = UF)) +
    geom_jitter(width = .1, alpha = 1) + 
    labs(
        x = "",
        y = "Avaliação numa escala de 1 a 6",
        title = "Todas as respostas",
        subtitle = "Cada IES com uma cor"
    ) + 
    facet_grid(reorder(categoria, media) ~ ., scales = "free_y") + 
    theme(legend.position = "bottom") + 
    coord_flip()
    
        
```


Interativo:
Mapas vizualizar informações por estado 

```{r}
respostas %>% 
    filter(IES == "UFCG") %>% 
    ggplot(aes(x = media, y = tema)) +
    geom_point()

```

